exasol/virtual-schema-common-document-files

- doc/changes/changes_0.2.0.md
- src/main/java/com/exasol/adapter/document/files/DocumentFilesAdapter.java
- src/main/java/com/exasol/adapter/document/files/FilesDataLoaderFactory.java
- src/main/java/com/exasol/adapter/document/files/FilesDataLoaderResolver.java
- src/main/java/com/exasol/adapter/document/files/JsonFilesDataLoaderFactory.java
- src/main/java/com/exasol/adapter/document/files/JsonLinesFilesDataLoaderFactory.java
- src/main/resources/META-INF/services/com.exasol.adapter.document.files.FilesDataLoaderFactory
- src/test/java/com/exasol/adapter/document/files/FilesDataLoaderResolverTest.java
> #16 Made document types extensible using service loader

- doc/changes/changes_0.2.0.md
- doc/user_guide/dialect_development_guide.md
- src/main/java/com/exasol/adapter/document/documentfetcher/files/AbstractFilesDocumentFetcher.java
- src/main/java/com/exasol/adapter/document/documentfetcher/files/FileLoader.java
- src/main/java/com/exasol/adapter/document/documentfetcher/files/InputStreamWithResourceName.java
- src/main/java/com/exasol/adapter/document/documentfetcher/files/JsonDocumentFetcher.java
- src/main/java/com/exasol/adapter/document/documentfetcher/files/JsonLinesDocumentFetcher.java
- src/main/java/com/exasol/adapter/document/documentfetcher/files/JsonLinesIterable.java
- src/main/java/com/exasol/adapter/document/documentfetcher/files/JsonLinesIterator.java
- src/main/java/com/exasol/adapter/document/documentfetcher/files/LoadedFile.java
- src/main/java/com/exasol/adapter/document/files/JsonLinesFilesDataLoaderFactory.java
- src/test/java/com/exasol/adapter/document/documentfetcher/files/JsonDocumentFetcherTest.java
- src/test/java/com/exasol/adapter/document/documentfetcher/files/JsonLinesIteratorTest.java
> Refactor/23 Added abstract doument fetcher

- doc/changes/changes_0.2.0.md
- src/main/java/com/exasol/adapter/document/documentfetcher/files/SegmentDescription.java
- src/main/java/com/exasol/adapter/document/documentfetcher/files/SegmentMatcher.java
- src/main/java/com/exasol/adapter/document/files/AbstractFilesDataLoaderFactory.java
- src/main/java/com/exasol/adapter/document/files/JsonFilesDataLoader.java
- src/main/java/com/exasol/adapter/document/files/JsonFilesDataLoaderFactory.java
- src/main/java/com/exasol/adapter/document/files/JsonLinesFilesDataLoaderFactory.java
- src/test/java/com/exasol/adapter/document/files/FilesDataLoaderResolverTest.java
> #25 Added abstract data loader factory

- doc/changes/changes_0.2.0.md
- pom.xml
- src/main/java/com/exasol/adapter/document/documentfetcher/files/InputDataException.java
- src/main/java/com/exasol/adapter/document/documentfetcher/files/JsonDocumentFetcher.java
- src/main/java/com/exasol/adapter/document/documentfetcher/files/JsonLinesIterator.java
- src/main/java/com/exasol/adapter/document/documentnode/json/JsonNodeFactory.java
- src/test/java/com/exasol/adapter/document/documentfetcher/files/JsonDocumentFetcherTest.java
- src/test/java/com/exasol/adapter/document/documentfetcher/files/JsonLinesDocumentFetcherTest.java
- src/test/java/com/exasol/adapter/document/documentfetcher/files/JsonLinesIteratorTest.java
> #13 Improved error messages

- doc/changes/changes_0.2.0.md
- src/main/java/com/exasol/adapter/document/documentfetcher/files/JsonDocumentFetcher.java
- src/main/java/com/exasol/adapter/document/documentfetcher/files/JsonLinesIterator.java
- src/test/java/com/exasol/adapter/document/documentfetcher/files/JsonDocumentFetcherTest.java
> #12: Fixed error message for empty json files

- doc/changes/changelog.md
- doc/changes/changes_0.3.0.md
- pom.xml
- src/main/java/com/exasol/adapter/document/documentfetcher/files/AbstractFilesDocumentFetcher.java
- src/main/java/com/exasol/adapter/document/documentfetcher/files/InputStreamWithResourceName.java
- src/main/java/com/exasol/adapter/document/documentfetcher/files/JsonDocumentFetcher.java
- src/main/java/com/exasol/adapter/document/documentfetcher/files/JsonLinesIterator.java
- src/test/java/com/exasol/adapter/document/documentfetcher/files/AbstractFilesDocumentFetcherTest.java
- src/test/java/com/exasol/adapter/document/documentfetcher/files/JsonDocumentFetcherTest.java
- src/test/java/com/exasol/adapter/document/documentfetcher/files/JsonLinesDocumentFetcherTest.java
- src/test/java/com/exasol/adapter/document/documentfetcher/files/JsonLinesIteratorTest.java
Closes #22 
This PR implements the API change from https://github.com/exasol/virtual-schema-common-document/pull/38
> #22 Added a column containing the the file name

- NOTICE
- doc/changes/changes_0.3.0.md
- pom.xml
- src/test/resources/logging.properties
> #38: Removed unnecessary dependencies

- doc/changes/changes_0.3.0.md
- pom.xml
- src/test/java/com/exasol/adapter/document/documentfetcher/files/AbstractFilesDocumentFetcherTest.java
- src/test/java/com/exasol/adapter/document/files/AbstractDocumentFilesAdapterIT.java
- src/test/resources/abstractIntegrationTests/dataTypeTests.jsonl
- src/test/resources/abstractIntegrationTests/mapDataTypesToDecimal.json
- src/test/resources/abstractIntegrationTests/mapDataTypesToJson.json
- src/test/resources/abstractIntegrationTests/mapDataTypesToVarchar.json
- src/test/resources/abstractIntegrationTests/mapJsonFile.json
- src/test/resources/abstractIntegrationTests/mapJsonLinesFile.json
- src/test/resources/abstractIntegrationTests/test.jsonl
- src/test/resources/abstractIntegrationTests/testData-1.json
- src/test/resources/abstractIntegrationTests/testData-2.json
> #40: Created abstract integration test

- NOTICE
- doc/changes/changes_0.3.0.md
- pom.xml
- src/main/java/com/exasol/adapter/document/documentfetcher/files/JsonDocumentFetcher.java
- src/main/java/com/exasol/adapter/document/documentfetcher/files/JsonLinesIterator.java
- src/main/java/com/exasol/adapter/document/documentnode/json/JsonNodeFactory.java
- src/main/java/com/exasol/adapter/document/files/FilesSelectionExtractor.java
- src/test/java/com/exasol/adapter/document/documentfetcher/files/JsonDocumentFetcherTest.java
- src/test/java/com/exasol/adapter/document/documentfetcher/files/JsonLinesIteratorTest.java
> #36: Added unified error codes

- doc/changes/changes_2.1.0.md
- src/test/java/com/exasol/adapter/document/files/AbstractDocumentFilesAdapterIT.java
- src/test/resources/abstractIntegrationTests/mapDataTypesToDecimal.json
- src/test/resources/abstractIntegrationTests/mapDataTypesToJson.json
- src/test/resources/abstractIntegrationTests/mapDataTypesToVarchar.json
- src/test/resources/abstractIntegrationTests/mapJsonFile.json
- src/test/resources/abstractIntegrationTests/mapJsonLinesFile.json
- src/test/resources/abstractIntegrationTests/mapParquetFile.json
> bug/62: Fixed unstable tests

- doc/changes/changelog.md
- doc/changes/changes_2.1.0.md
- doc/user_guide/user_guide.md
- pom.xml
- src/main/java/com/exasol/adapter/document/files/DocumentFilesAdapter.java
- src/main/java/com/exasol/adapter/document/files/FilesQueryPlanner.java
- src/main/java/com/exasol/adapter/document/files/SourceString.java
- src/test/java/com/exasol/adapter/document/files/AbstractDocumentFilesAdapterIT.java
- src/test/java/com/exasol/adapter/document/files/DocumentFilesAdapterTest.java
- src/test/java/com/exasol/adapter/document/files/FilesQueryPlannerTest.java
- src/test/java/com/exasol/adapter/document/files/SourceStringTest.java
- src/test/resources/abstractIntegrationTests/mapJsonLinesFileWithStrangeExtension.json
> feature/59: Allowed overriding of document type detected by ending

- .github/workflows/release_droid_upload_github_release_assets.yml
- dependencies.md
- doc/changes/changelog.md
- doc/changes/changes_2.2.0.md
- pom.xml
- src/test/java/com/exasol/adapter/document/files/AbstractDocumentFilesAdapterIT.java
> refactor/67: Moved performance-test-recorder to its own repo

- .gitignore
- dependencies.md
- doc/changes/changes_2.2.0.md
- pom.xml
- quickBuild.sh
- src/test/java/com/exasol/adapter/document/files/AbstractDocumentFilesAdapterIT.java
> feature/69: Added more tests for parquet types

- dependencies.md
- doc/changes/changelog.md
- doc/changes/changes_2.2.1.md
- pom.xml
- src/main/java/com/exasol/adapter/document/documentfetcher/files/JsonDocumentFetcher.java
- src/main/java/com/exasol/adapter/document/documentfetcher/files/JsonLinesIterator.java
- src/main/java/com/exasol/adapter/document/documentnode/json/JsonArrayNode.java
- src/main/java/com/exasol/adapter/document/documentnode/json/JsonNodeFactory.java
- src/main/java/com/exasol/adapter/document/documentnode/json/JsonObjectNode.java
- src/test/java/com/exasol/adapter/document/documentnode/json/JsonArrayNodeTest.java
- src/test/java/com/exasol/adapter/document/documentnode/json/JsonNodeFactoryTest.java
- src/test/java/com/exasol/adapter/document/documentnode/json/JsonObjectNodeTest.java
> refactor/71: Replaced javax.json by jakarta.json

- doc/changes/changelog.md
- doc/changes/changes_4.0.0.md
- pom.xml
- src/main/java/com/exasol/adapter/document/documentfetcher/files/FileLoader.java
- src/main/java/com/exasol/adapter/document/documentfetcher/files/FilesDocumentFetcher.java
- src/main/java/com/exasol/adapter/document/documentfetcher/files/JsonDocumentFetcher.java
- src/main/java/com/exasol/adapter/document/documentfetcher/files/JsonLinesDocumentFetcher.java
- src/main/java/com/exasol/adapter/document/documentfetcher/files/JsonLinesIterator.java
- src/main/java/com/exasol/adapter/document/documentfetcher/files/parquet/ParquetDocumentFetcher.java
- src/main/java/com/exasol/adapter/document/files/FileTypeSpecificDocumentFetcher.java
- src/main/java/com/exasol/adapter/document/files/FilesDocumentFetcherFactory.java
- src/test/java/com/exasol/adapter/document/documentfetcher/files/FilesDocumentFetcherTest.java
- src/test/java/com/exasol/adapter/document/documentfetcher/files/JsonLinesIteratorTest.java
- src/test/java/com/exasol/adapter/document/files/FilesDocumentFetcherFactoryTest.java
- src/test/java/com/exasol/adapter/document/files/FilesQueryPlannerTest.java
> updated vs-common-document

- .github/workflows/broken_links_checker.yml
- dependencies.md
- doc/changes/changelog.md
- doc/changes/changes_6.0.2.md
- doc/changes/changes_7.0.2.md
- pk_generated_parent.pom
- pom.xml
> Upgrade dependencies

- README.md
- dependencies.md
- doc/changes/changelog.md
- doc/changes/changes_7.1.2.md
- pk_generated_parent.pom
- pom.xml
> #113: Added reference to list of Virtual Schema dialects.

- doc/changes/changes_7.1.2.md
> prepare release 7.1.2

- dependencies.md
- doc/changes/changelog.md
- doc/changes/changes_7.1.3.md
- pk_generated_parent.pom
- pom.xml
> Updated dependencies

- doc/changes/changelog.md
- doc/changes/changes_7.1.4.md
- pk_generated_parent.pom
- pom.xml
> updated udf-debugging-java

- doc/changes/changes_7.1.1.md
- doc/changes/changes_7.3.0.md
- pom.xml
- src/main/java/com/exasol/adapter/document/documentfetcher/files/csv/CsvHeaderDetector.java
- src/main/java/com/exasol/adapter/document/documentfetcher/files/csv/CsvParser.java
- src/main/java/com/exasol/adapter/document/documentfetcher/files/csv/CsvSchemaFetcher.java
- src/main/java/com/exasol/adapter/document/documentfetcher/files/parquet/ParquetSchemaFetcher.java
- src/main/java/com/exasol/adapter/document/files/FileTypeSpecificSchemaFetcher.java
- src/main/java/com/exasol/adapter/document/files/FilesSchemaFetcher.java
- src/test/java/com/exasol/adapter/document/documentfetcher/files/csv/CsvHeaderDetectorTest.java
- src/test/java/com/exasol/adapter/document/documentfetcher/files/csv/CsvSchemaFetcherTest.java
- src/test/java/com/exasol/adapter/document/documentfetcher/files/parquet/ParquetSchemaFetcherTest.java
- src/test/java/com/exasol/adapter/document/files/AbstractDocumentFilesAdapterIT.java
- src/test/java/com/exasol/adapter/document/files/DocumentFilesAdapterTest.java
- src/test/java/com/exasol/adapter/document/files/FileTypeSpecificSchemaFetcherTest.java
> #131: Detect presence of CSV header

- doc/changes/changelog.md
- doc/changes/changes_7.3.2.md
- pk_generated_parent.pom
- pom.xml
> #136: Add missing classes to test-jar

- doc/changes/changelog.md
- doc/changes/changes_7.3.3.md
- pk_generated_parent.pom
- pom.xml
> #138: Upgraded dependencies

- .pre-commit-config.yaml
- dependencies.md
- doc/changes/changelog.md
- doc/changes/changes_7.3.5.md
- pk_generated_parent.pom
- pom.xml
> #144: Fix CVE-2023-39410 in org.apache.avro:avro

- .github/workflows/broken_links_checker.yml
- .github/workflows/ci-build-next-java.yml
- .github/workflows/ci-build.yml
- .github/workflows/dependencies_update.yml
- dependencies.md
- doc/changes/changelog.md
- doc/changes/changes_8.0.4.md
- pk_generated_parent.pom
- pom.xml
> #161 : CVE-2024-36114: io.airlift:aircompressor:jar:0.21:compile

- dependencies.md
- doc/changes/changelog.md
- doc/changes/changes_8.1.1.md
- pk_generated_parent.pom
- pom.xml
- src/test/java/com/exasol/adapter/document/files/AbstractDocumentFilesAdapterIT.java
This adds an integration test that verifies, that
```sql
ALTER VIRTUAL SCHEMA <schema> REFRESH
```
works for file based virtual schemas.
> Add integration test for ALTER VIRTUAL SCHEMA <schema> REFRESH

- doc/changes/changelog.md
- doc/changes/changes_8.1.8.md
- doc/changes/changes_8.1.9.md
- pk_generated_parent.pom
- pom.xml
- src/main/java/com/exasol/adapter/document/files/FilesDocumentFetcherFactory.java
- src/main/java/com/exasol/adapter/document/files/stringfilter/StringFilterAnd.java
- src/test/java/com/exasol/adapter/document/files/FileTypeSpecificDocumentFetcherFactoryTest.java
- src/test/java/com/exasol/adapter/document/files/FilesDocumentFetcherFactoryTest.java
- src/test/java/com/exasol/adapter/document/files/FilesQueryPlannerTest.java
- src/test/java/com/exasol/adapter/document/files/stringfilter/StringFilterAndTest.java
> Added logging for source filter contradictions 

- .github/workflows/dependencies_check.yml
- doc/changes/changelog.md
- doc/changes/changes_8.1.12.md
- pk_generated_parent.pom
- pom.xml
> Fix for CVE-2025-48924
